# config/queue.yml
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default
  # Use main database connection for development
  # No separate database configuration needed

test:
  <<: *default
  # Use main database connection for test
  # No separate database configuration needed

production:
  <<: *default
  # Production uses separate databases as configured in database.yml